-- Generated by Oracle SQL Developer REST Data Services 19.2.1.247.2212
-- Exported REST Definitions from ORDS Schema Version 3.0.9.348.07.16
-- Schema: GRUPO7   Date: Thu Dec 19 18:42:31 GMT 2019
--

BEGIN

    ORDS.ENABLE_SCHEMA(p_enabled => TRUE,
                       p_schema => 'GRUPO7',
                       p_url_mapping_type => 'BASE_PATH',
                       p_url_mapping_pattern => 'grupo7',
                       p_auto_rest_auth => FALSE);

    commit;

END;
/

BEGIN

    ORDS.ENABLE_OBJECT(p_enabled => TRUE,
                       p_schema => 'GRUPO7',
                       p_object => 'DATAFILE_STATUS',
                       p_object_type => 'TABLE',
                       p_object_alias => 'datafile_status',
                       p_auto_rest_auth => FALSE);

    commit;

END;
/

BEGIN
    ORDS.ENABLE_OBJECT(p_enabled => TRUE,
                       p_schema => 'GRUPO7',
                       p_object => 'DATAFILE',
                       p_object_type => 'TABLE',
                       p_object_alias => 'datafile',
                       p_auto_rest_auth => FALSE);

    commit;

END;
/

BEGIN

    ORDS.ENABLE_OBJECT(p_enabled => TRUE,
                       p_schema => 'GRUPO7',
                       p_object => 'DB',
                       p_object_type => 'TABLE',
                       p_object_alias => 'db',
                       p_auto_rest_auth => FALSE);

    commit;

END;
/

BEGIN

    ORDS.ENABLE_OBJECT(p_enabled => TRUE,
                       p_schema => 'GRUPO7',
                       p_object => 'DB_STATUS',
                       p_object_type => 'TABLE',
                       p_object_alias => 'db_status',
                       p_auto_rest_auth => FALSE);

    commit;

END;
/

BEGIN

    ORDS.ENABLE_OBJECT(p_enabled => TRUE,
                       p_schema => 'GRUPO7',
                       p_object => 'TABLESPACE',
                       p_object_type => 'TABLE',
                       p_object_alias => 'tablespace',
                       p_auto_rest_auth => FALSE);

    commit;

END;
/

BEGIN

    ORDS.ENABLE_OBJECT(p_enabled => TRUE,
                       p_schema => 'GRUPO7',
                       p_object => 'USERS',
                       p_object_type => 'TABLE',
                       p_object_alias => 'users',
                       p_auto_rest_auth => FALSE);

    commit;

END;
/
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'GRUPO7',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'grupo7',
      p_auto_rest_auth      => FALSE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => 'personalizado',
      p_base_path      => '/personalizado/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.SET_MODULE_ORIGINS_ALLOWED(
      p_module_name     => 'personalizado',
      p_origins_allowed => 'localhost');      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'personalizado',
      p_pattern        => '1',
      p_priority       => 0,
      p_etag_type      => 'NONE',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'personalizado',
      p_pattern        => '1',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT d.ID, d.NAME, d.AUTO_EXTENSIBLE, d.STATUS, d.MAX_BYTES, d.BYTES, t.NAME AS TABLESPACE_NAME FROM GRUPO7.DATAFILE d
INNER JOIN tablespace t on d.tablespace_id = t.id'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'personalizado',
      p_pattern        => '2',
      p_priority       => 0,
      p_etag_type      => 'NONE',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'personalizado',
      p_pattern        => '2',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  100,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT BYTES, TIMESTAMP FROM DATAFILE_STATUS
    WHERE datafile_id = :datafile_id'
      );


  COMMIT; 
END;
/